database:
  user: postgres
  password: korabl
  dbname: moon_writer
  addr: 127.0.0.1:5432
  host: localhost
  port: 5432
  driver: postgres
  sslmode: disable
log:
  forcecolors: true
  fulltimestamp: true